[tool.poetry]
name = "my-simple-rent"
version = "0.1.0"
description = ""
authors = ["Pasechneek <danil.merkurev@yandex.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12"
django = "*"
python-dotenv = "*"
mysqlclient = ">=2.2.1"
poetry-core = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"